### ISSUE TITLE
example code does not work for polblogs.npz dataset

### ISSUE THREAD

**Issue by Luckick** [abojchevski/node_embedding_attack#2]
The following error shows up:
 
`Traceback (most recent call last):
  File "/home/qil15006/2020Spring/NodeAttack/ori_example.py", line 49, in <module>
    b_eig_flips = baseline_eigencentrality_top_flips(adj_matrix, candidates, n_flips)
  File "/home/qil15006/2020Spring/NodeAttack/node_embedding_attack/perturbation_attack.py", line 293, in baseline_eigencentrality_top_flips
    eigcentrality_scores = np.array([eigcentrality_scores[tuple(cnd)] for cnd in candidates])
  File "/home/qil15006/2020Spring/NodeAttack/node_embedding_attack/perturbation_attack.py", line 293, in <listcomp>
    eigcentrality_scores = np.array([eigcentrality_scores[tuple(cnd)] for cnd in candidates])
KeyError: (21, 21)`

**Comment by abojchevski** [comment]
The issue was that the removal of self-loops was missing from the `standardize` function. The fix is now pushed.

**Comment by Luckick** [comment]
It works after remove self loop. Thank you! 

Another finding is that in this dataset, the adjacency matrix is not binary, e.g there are some values are 2. 
Is this normal?

**Comment by abojchevski** [comment]
You are right. This is not expected. I use an internal library to standardize the graphs (make them undirected, unweighted, etc.) and the code for unweighted was not added to this repo. This is fixed with the latest commit.
