### ISSUE TITLE
Applying this method on nxd matrix instead on nxn

### ISSUE THREAD

**Issue by chetankm1992** [abojchevski/node_embedding_attack#4]
Hi,

I know this method is for adjacency matrix/graph whose size is nxn but I am thinking to apply on nxd matrix which is not really adjacency matrix. Is there way to modify this method and use it for nxd matrix.

Thanks.

**Comment by abojchevski** [comment]
Applying it directly would not work. However, it should be possible to derive a similar approach, e.g. by using singular value perturbation (instead of eigenvalue perturbation).
